local _, LibWidgets = ...;

-- frame
LIBWIDGETS_DEFAULT_CREATEFRAME_FRAMEPARENT = UIParent
LIBWIDGETS_DEFAULT_CREATEFRAME_FRAMEXSIZE = 100;
LIBWIDGETS_DEFAULT_CREATEFRAME_FRAMEYSIZE = 100;
LIBWIDGETS_DEFAULT_CREATEFRAME_POS = "TOPLEFT";
LIBWIDGETS_DEFAULT_CREATEFRAME_LEFT_OFFSET = 80;
LIBWIDGETS_DEFAULT_CREATEFRAME_TOP_OFFSET = -80;
LIBWIDGETS_DEFAULT_CREATEFRAME_ALPHA = 0.75;

-- frame title
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_FRAMEXSIZE = 96;
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_FRAMEYSIZE = 32;
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_POS = "TOPLEFT";
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_LEFT_OFFSET = 2;
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_TOP_OFFSET = 0;
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_ALPHA = 1;

LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_COLUMN_ALPHA = 1;
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_FONT = "GameFontWhite";
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_TEXT_POS = "LEFT";
LIBWIDGETS_DEFAULT_CREATEFRAME_TITLE_TEXT_LEFTOFFSET = 8;

--LIBWIDGETS_DEFAULT_CREATEFRAME_
--LIBWIDGETS_DEFAULT_CREATEFRAME_
--LIBWIDGETS_DEFAULT_CREATEFRAME_