local _, LibWidgets = ...;

LIBWIDGETS_DEFAULT_CREATEBUTTON_CLOSE_TEMPLATE = "UIPanelCloseButton";
LIBWIDGETS_DEFAULT_CREATEBUTTON_CLOSE_TEXTURE = nil;
LIBWIDGETS_DEFAULT_CREATEBUTTON_CLOSE_HIGHLIGHT_TEXTURE = nil;

LIBWIDGETS_DEFAULT_CREATEBUTTON_OPTION_TEMPLATE = nil;
LIBWIDGETS_DEFAULT_CREATEBUTTON_OPTION_TEXTURE = "Interface\\Icons\\Trade_Engineering.blp";
LIBWIDGETS_DEFAULT_CREATEBUTTON_OPTION_HIGHLIGHT_TEXTURE = "Interface\\Buttons\\UI-Panel-MinimizeButton-Highlight.blp";

LIBWIDGETS_DEFAULT_CREATEBUTTON_TEMPLATE = nil;
LIBWIDGETS_DEFAULT_CREATEBUTTON_TEXTURE = nil;
LIBWIDGETS_DEFAULT_CREATEBUTTON_TOOLTIP_ANCHOR = "ANCHOR_CURSOR";