local _, LibWidgets = ...;

LIBWIDGETS_DEFAULT_SETBACKDROP_BGFILE = "Interface\\Tooltips\\UI-Tooltip-Background";
LIBWIDGETS_DEFAULT_SETBACKDROP_TILE = false;
LIBWIDGETS_DEFAULT_SETBACKDROP_TILESIZE = 32;
LIBWIDGETS_DEFAULT_SETBACKDROP_EDGEFILE = "Interface\\Tooltips\\UI-Tooltip-Border";
LIBWIDGETS_DEFAULT_SETBACKDROP_EDGESIZE = 8;
LIBWIDGETS_DEFAULT_SETBACKDROP_INSET_LEFT = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_INSET_TOP = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_INSET_RIGHT = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_INSET_BOTTOM = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_BACKDROPCOLOR = "0.1, 0.1, 0.1, 1";
LIBWIDGETS_DEFAULT_SETBACKDROP_BACKDROPBORDERCOLOR = "0, 0, 0, 1";

-- title backdrop
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_BGFILE = "Interface\\Tooltips\\UI-Tooltip-Background";
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_TILE = false;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_TILESIZE = 32;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_EDGESIZE = 8;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_EDGEFILE = "Interface\\Tooltips\\UI-Tooltip-Border";
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_INSET_LEFT = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_INSET_TOP = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_INSET_RIGHT = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_INSET_BOTTOM = 4;
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_BACKDROPCOLOR = "0.1, 0.1, 0.1, 1";
LIBWIDGETS_DEFAULT_SETBACKDROP_TITLE_BACKDROPBORDERCOLOR = "0, 0, 0, 1";