local _, LibWidgets = ...;

LIBWIDGETS_DEFAULT_SETPOINT_ANCHOR = "CENTER";
--LIBWIDGETS_DEFAULT_SETPOINT_RELATIVE_FRAME = UIParent;
--LIBWIDGETS_DEFAULT_SETPOINT_RELATIVE_POINT = "CENTER";
LIBWIDGETS_DEFAULT_SETPOINT_OFSX = 40;
LIBWIDGETS_DEFAULT_SETPOINT_OFSY = -40;